name: "Advanced Git Sync"
description: "Synchronize GitHub repository with GitLab including branches, PRs, and issues"
author: "vikshan"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}

  GITLAB_TOKEN:
    description: "GitLab token for authentication"
    required: false

  CONFIG_PATH:
    description: "Path to the sync configuration file"
    required: false
    default: ".github/sync-config.yml"

runs:
  using: "composite"
  steps:
    - name: Backup Original Project Dependencies
      shell: bash
      run: |
        # Backup existing package.json and bun.lockb if they exist
        if [ -f package.json ]; then
          cp package.json package.json.original-backup
        fi
        if [ -f bun.lockb ]; then
          cp bun.lockb bun.lockb.original-backup
        fi

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: v1.2.14

    - name: Create Minimal Dependencies Package
      shell: bash
      run: |
        # Create a minimal package.json with only required dependencies
        echo '{
          "dependencies": {
            "@actions/core": "^1.11.1",
            "@actions/github": "^6.0.0",
            "@gitbeaker/rest": "^41.3.0",
            "@octokit/rest": "^21.0.2",
            "deepmerge": "^4.3.1",
            "js-yaml": "^4.1.0",
            "zod": "^3.23.8"
          }
        }' > package.json

    - name: Install Action Dependencies
      shell: bash
      run: |
        # Install only action-specific dependencies
        bun install

    - name: Run Advanced Git Sync
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_GITLAB_TOKEN: ${{ inputs.GITLAB_TOKEN }}
        INPUT_CONFIG_PATH: ${{ inputs.CONFIG_PATH }}
      run: bun run ${{ github.action_path }}/dist/index.js

    - name: Post-Job Cleanup
      if: always()
      shell: bash
      run: bun ${{ github.action_path }}/scripts/postjob.js

branding:
  icon: "git-branch"
  color: "orange"
